#!/bin/sh

if [ "${POSTUREPATH}" == "" ]; then
  echo "缺少POSTUREPATH配置 (You missed the configuration of POSTUREPATH)"
  exit 1
fi
cd $POSTUREPATH

currentDir=$(pwd)
. $currentDir/include/function.sh
COMMAND=$1

if [ "${COMMAND}" == "hooking" ]; then
  hooking $currentDir
elif [ "${COMMAND}" == "adjust" ]; then
  checkConfig && adjust
elif [ "${COMMAND}" == "info" ]; then
  echo "The list of information"
  echo "> lang = ${lang}"
else
  echo "Unknown command: ${COMMAND}"
fi
