#!/bin/sh
if [ "${POSTUREPATH}" == "" ]; then
  echo "缺少POSTUREPATH配置 (You missed the configuration of POSTUREPATH)"
  exit 1
fi
cd $POSTUREPATH

currentDir=$(pwd)
. $currentDir/include/function.sh

printLogo
echo "温馨提示: 请注意是否拉取了正确的分支 (Warm tips: Please pull the correct branch)"
