#!/bin/sh
if [ "${POSTUREPATH}" == "" ]; then
  echo "缺少POSTUREPATH配置 (You missed the configuration of POSTUREPATH)"
  exit 1
fi
cd $POSTUREPATH

currentDir=$(pwd)
. $currentDir/include/function.sh

printLogo
echo "温馨提示: 请及时拉取分支的最新代码 (Warm tips: Please pull the latest code in time)"
