#!/bin/sh
if [ "${POSTUREPATH}" == "" ]; then
  echo "缺少POSTUREPATH配置 (You missed the configuration of POSTUREPATH)"
  exit 1
fi
. $POSTUREPATH/include/function.sh

printLogo
echo "温馨提示: 请及时拉取分支的最新代码 (Warm tips: Please pull the latest code in time)"

newBranch=$(git reflog | awk 'NR==1{ print $8; }')
echo "> 当前分支: \033[33m${newBranch}\033[0m"

changeDirection=$(git reflog | awk 'NR==1{ print $6 " -> " $8; exit }')
echo "> 分支切换顺序 (the direction of branch switch): \033[33m${changeDirection}\033[0m"
