#!/bin/sh

if [ "${POSTURE_PATH}" == "" ]; then
    echo "缺少POSTURE_PATH配置 (You missed the configuration of POSTURE_PATH)"
    exit 1
fi
. $POSTURE_PATH/include/sdk.sh

newBranch=$(git reflog | awk 'NR==1{ print $8; }')
changeDirection=$(git reflog | awk 'NR==1{ print $6 " -> " $8; exit }')

if [ "${newBranch}" == "" ] || [ "${changeDirection}" == "" ] ; then
    exit 0
fi

print_logo
echo "温馨提示: 请及时拉取分支的最新代码 (Warm tips: Please pull the latest code in time)"

echo "> 当前分支: \033[33m${newBranch}\033[0m"
echo "> 分支切换顺序 (the direction of branch switch): \033[33m${changeDirection}\033[0m"
