#!/bin/sh

if [ "${POSTURE_PATH}" == "" ]; then
    echo "缺少POSTURE_PATH配置 (You missed the configuration of POSTURE_PATH)"
    exit 1
fi
. $POSTURE_PATH/include/sdk.sh

branchName=$(git symbolic-ref --short -q HEAD)
commitId=$(git log -1 HEAD --pretty=format:"%h")
commitMsg=$(git log -1 HEAD --pretty=format:"%s" | sed s/[[:space:]]//g)
commitUser=$(git log -1 HEAD --pretty=format:"%cn" | sed s/[[:space:]]//g)
write_commit_log ${commitUser} ${branchName} ${commitId} ${commitMsg}

exit 1
